# Ruta: /cloudbuild.yaml
steps:
# --- PASO 1: Instalar dependencias del Panel de Admin (React) ---
- name: 'gcr.io/cloud-builders/npm'
  id: 'Admin-Panel-Install'
  args: ['install']
  dir: 'admin-panel'

# --- PASO 2: Construir el Panel de Admin (React) ---
# Este paso crea la carpeta 'admin-panel/build' que Firebase necesita.
- name: 'gcr.io/cloud-builders/npm'
  id: 'Admin-Panel-Build'
  args: ['run', 'build']
  dir: 'admin-panel'
  wait_for: ['Admin-Panel-Install']

# --- PASO 3: Instalar dependencias para las Cloud Functions ---
- name: 'gcr.io/cloud-builders/npm'
  id: 'Functions-Install'
  args: ['install']
  dir: 'functions'
  
# --- PASO 4: Desplegar a Firebase (Hosting y Functions a la vez) ---
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy-to-Firebase'
  entrypoint: 'firebase'
  args:
    - 'deploy'
    - '--project'
    - '${PROJECT_ID}' # Variable automática de Cloud Build
    - '--only=hosting,functions'
    - '--force'
  wait_for: ['Admin-Panel-Build', 'Functions-Install']

# --- PASO 5: Desplegar el Backend de Orquestación a Cloud Run ---
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy-to-Cloud-Run'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - 'orchestration-backend'
    - '--source=.'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--update-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,ORCHESTRATOR_ASSISTANT_ID=ORCHESTRATOR_ASSISTANT_ID:latest,ASISTENTE_ID=ASISTENTE_ID:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest'
  wait_for: ['Deploy-to-Firebase']

# Aumenta el tiempo de espera para evitar timeouts
timeout: '1600s'

# --- SECCIÓN CORREGIDA: OPCIONES DE LOGGING ---
# Esta sección soluciona el error de "Failed to trigger build"
options:
  logging: CLOUD_LOGGING_ONLY
