# =====================================================================================
# cloudbuild.yaml con Diagnóstico Avanzado
# =====================================================================================
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy-Backend-to-Cloud-Run'
    entrypoint: 'gcloud'
    args:
      - '--verbosity=debug'  # <-- AÑADIDO: Muestra los logs de depuración
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--project'
      - '${PROJECT_ID}'
      - '--timeout=300s'
      - '--concurrency=80'
      - '--cpu=1'
      - '--memory=512Mi'

  # ... (resto del archivo sin cambios) ...

  - name: 'node:18'
    id: 'Install-Firebase-Tools'
    entrypoint: 'npm'
    args: ['install', 'firebase-tools']

  - name: 'node:18'
    id: 'Deploy-Frontend-to-Firebase'
    entrypoint: './node_modules/.bin/firebase'
    args:
      - 'deploy'
      - '--project'
      - '${_FIREBASE_PROJECT_ALIAS}'
      - '--only'
      - 'hosting'
      - '--force'
    waitFor: ['Install-Firebase-Tools']

substitutions:
  _SERVICE_NAME: 'orchestrator'
  _FIREBASE_PROJECT_ALIAS: 'prod'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET