options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'europe-west1-docker.pkg.dev/mi-proyecto-12345/orchestrator-repo/orchestrator',
      '.'
    ]
# resto de pasos...


steps:
# 1. Build & push de la imagen
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'europe-west1-docker.pkg.dev/mi-proyecto-12345/orchestrator-repo/orchestrator',
      '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'europe-west1-docker.pkg.dev/mi-proyecto-12345/orchestrator-repo/orchestrator'
    ]

# 2. Despliegue en Cloud Run, inyectando secretos
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # extrae los secretos y los pasa como env-vars
      API_KEY=$(gcloud secrets versions access latest --secret=openai-api-key)
      ASST_ID=$(gcloud secrets versions access latest --secret=assistant-id)
      AUD_ID=$(gcloud secrets versions access latest --secret=auditor-id)

      gcloud run deploy orchestrator \
        --image=europe-west1-docker.pkg.dev/mi-proyecto-12345/orchestrator-repo/orchestrator \
        --region=europe-west1 \
        --platform=managed \
        --allow-unauthenticated \
        --set-env-vars \
          OPENAI_API_KEY="$API_KEY",\
          ASISTENTE_ID="$ASST_ID",\
          AUDITOR_ID="$AUD_ID"

# Define aquí la imagen para que Cloud Build la registre como artefacto final
images:
  - 'europe-west1-docker.pkg.dev/mi-proyecto-12345/orchestrator-repo/orchestrator'

# Configuración de secretos disponibles para Cloud Build
availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/openai-api-key/versions/latest"
      env: "OPENAI_API_KEY"
    - versionName: "projects/${PROJECT_ID}/secrets/assistant-id/versions/latest"
      env: "ASISTENTE_ID"
    - versionName: "projects/${PROJECT_ID}/secrets/auditor-id/versions/latest"
      env: "AUDITOR_ID"
